[package]
name = "uhcreloaded-reports"
version = "0.1.0"
authors = ["Amaury Carrade <amaury@carrade.eu>"]
edition = "2018"

[dependencies]
datetime = "0.4.*"
failure = "0.1.*"
failure_derive = "0.1.*"
rocket = "0.4.*"
rocket_contrib = { version = "0.4.*", default-features = false, features = ["json", "serve", "tera_templates"]}
serde = "1.0.*"
serde_json = "1.0.*"
serde_derive = "1.0.*"
uuid = { version = "0.7", features = ["serde", "v4"] }

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "uhcreloaded_reports"
path = "src/main.rs"
